# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wav2letter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wav2letter.proto',
  package='wav2letter',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10wav2letter.proto\x12\nwav2letter\">\n\x0b\x42yte_Stream\x12\x0f\n\x07\x62stream\x18\x01 \x01(\x0c\x12\x0b\n\x03\x65os\x18\x02 \x01(\x08\x12\x11\n\tunique_id\x18\x03 \x01(\x05\";\n\x0cTrans_Stream\x12\x0f\n\x07tstream\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\x05\x12\x0b\n\x03\x65nd\x18\x03 \x01(\x05\x32R\n\x0f\x65\x63ho_bytestream\x12?\n\x06Search\x12\x17.wav2letter.Byte_Stream\x1a\x18.wav2letter.Trans_Stream(\x01\x30\x01\x62\x06proto3'
)




_BYTE_STREAM = _descriptor.Descriptor(
  name='Byte_Stream',
  full_name='wav2letter.Byte_Stream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bstream', full_name='wav2letter.Byte_Stream.bstream', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eos', full_name='wav2letter.Byte_Stream.eos', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unique_id', full_name='wav2letter.Byte_Stream.unique_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=94,
)


_TRANS_STREAM = _descriptor.Descriptor(
  name='Trans_Stream',
  full_name='wav2letter.Trans_Stream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tstream', full_name='wav2letter.Trans_Stream.tstream', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start', full_name='wav2letter.Trans_Stream.start', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='wav2letter.Trans_Stream.end', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['Byte_Stream'] = _BYTE_STREAM
DESCRIPTOR.message_types_by_name['Trans_Stream'] = _TRANS_STREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Byte_Stream = _reflection.GeneratedProtocolMessageType('Byte_Stream', (_message.Message,), {
  'DESCRIPTOR' : _BYTE_STREAM,
  '__module__' : 'wav2letter_pb2'
  # @@protoc_insertion_point(class_scope:wav2letter.Byte_Stream)
  })
_sym_db.RegisterMessage(Byte_Stream)

Trans_Stream = _reflection.GeneratedProtocolMessageType('Trans_Stream', (_message.Message,), {
  'DESCRIPTOR' : _TRANS_STREAM,
  '__module__' : 'wav2letter_pb2'
  # @@protoc_insertion_point(class_scope:wav2letter.Trans_Stream)
  })
_sym_db.RegisterMessage(Trans_Stream)



_ECHO_BYTESTREAM = _descriptor.ServiceDescriptor(
  name='echo_bytestream',
  full_name='wav2letter.echo_bytestream',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=157,
  serialized_end=239,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='wav2letter.echo_bytestream.Search',
    index=0,
    containing_service=None,
    input_type=_BYTE_STREAM,
    output_type=_TRANS_STREAM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ECHO_BYTESTREAM)

DESCRIPTOR.services_by_name['echo_bytestream'] = _ECHO_BYTESTREAM

# @@protoc_insertion_point(module_scope)
