# ==================================================================
# module list
# ------------------------------------------------------------------
# Ubuntu           18.04
# cmake            3.16.5       (git)
# MKL              2018.4-057   (apt)
# libsndfile       bef2abc      (git)
# KenLM            e47088d      (git)
# python           3.6          (apt)
# grpc             1.33.1       (git)
# ==================================================================

FROM ubuntu:18.04

RUN APT_INSTALL="apt install -y --no-install-recommends" && \
    apt update && \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
        build-essential \
        ca-certificates \
        wget \
        git \
        apt-utils \
        vim \
        emacs \
        nano \
        htop \
        g++ \
        libssl-dev \
        gnupg2 \
        cmake \
        # for MKL
        apt-transport-https \
        # for libsndfile
        autoconf automake autogen build-essential libasound2-dev libsndfile-dev \
        libflac-dev libogg-dev libtool libvorbis-dev pkg-config python \
        # FFTW
        libfftw3-dev \
        # for kenlm
        zlib1g-dev libbz2-dev liblzma-dev libboost-all-dev \
        # gflags
        libgflags-dev libgflags2.2 \
        # for receipts data processing
        sox && \
# ==================================================================
# KenLM https://github.com/kpu/kenlm
# ------------------------------------------------------------------
    cd /root && git clone https://github.com/kpu/kenlm.git && \
    cd kenlm && git checkout e47088ddfae810a5ee4c8a9923b5f8071bed1ae8 && \
    mkdir build && cd build && \
    cmake .. && \
    make -j$(nproc) && make -j$(nproc) install && \
# ==================================================================
# MKL https://software.intel.com/en-us/mkl
# ------------------------------------------------------------------
    cd /tmp && wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB && \
    apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB && \
    wget https://apt.repos.intel.com/setup/intelproducts.list -O /etc/apt/sources.list.d/intelproducts.list && \
    sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list' && \
    apt-get update && DEBIAN_FRONTEND=noninteractive $APT_INSTALL intel-mkl-64bit-2018.4-057 && \
# ==================================================================
# Upgrade CMake
# ------------------------------------------------------------------
    cd /tmp && \
    wget https://github.com/Kitware/CMake/releases/download/v3.16.5/cmake-3.16.5.tar.gz && \
    tar -zxvf cmake-3.16.5.tar.gz && \
    cd cmake-3.16.5 && \
    ./bootstrap && \
    make -j2 && \
    make install && \
# ==================================================================
# Install gRPC
# ------------------------------------------------------------------
    cd /tmp && \
    git clone --recurse-submodules -b v1.33.1 https://github.com/grpc/grpc && \
    cd grpc && \
    mkdir -p build && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DgRPC_INSTALL=ON .. && \
    make -j2 && \
    make install && \
# ==================================================================
# config & cleanup
# ------------------------------------------------------------------
    ldconfig && \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* /tmp/*
